[package]
name = "algorithm-design-analysis"
version = "0.0.1"
authors = ["andelf <andelf@gmail.com>"]

[features]
default = []
dev = ["clippy"]

[dependencies]
clippy = {version = "*", optional = true}
rand = "*"
petgraph = "*"
rustc-serialize = "*"
itertools = "*"
